In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('IrisDataset.csv')

In [5]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
dataset.shape

(150, 5)

In [11]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [15]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[ 5.25582889e-01,  8.11067169e-01,  9.88473342e-01,
         1.49228158e+00],
       [-3.75416349e-01, -1.51179823e+00,  5.72325095e-02,
        -1.13761376e-01],
       [ 1.68401048e+00, -1.18078991e-01,  1.27948610e+00,
         1.22460775e+00],
       [ 2.45629554e+00, -1.04722515e+00,  1.86151162e+00,
         1.49228158e+00],
       [-5.04130526e-01,  1.97249987e+00, -1.39783129e+00,
        -1.05061976e+00],
       [ 1.81272466e+00,  3.46494089e-01,  1.33768865e+00,
         8.23097013e-01],
       [ 7.83011243e-01,  3.46494089e-01,  9.30270790e-01,
         1.49228158e+00],
       [ 1.07261814e-02,  2.20478641e+00, -1.45603384e+00,
        -1.31829359e+00],
       [-5.04130526e-01,  1.97249987e+00, -1.16502108e+00,
        -1.05061976e+00],
       [-2.46702172e-01, -1.18078991e-01,  2.31840166e-01,
         1.53912450e-01],
       [-1.17987995e-01, -5.82652071e-01,  2.31840166e-01,
         1.53912450e-01],
       [ 2.68154535e-01, -1.18078991e-01,  6.39258030e-01,
      

In [19]:
X_test

array([[ 1.5552963 ,  0.34649409,  0.58105548,  0.28774936],
       [-1.53384394,  0.81106717, -1.33962874, -1.18445668],
       [ 0.52558289, -0.35036553,  0.34824527,  0.15391245],
       [ 1.16915377, -0.11807899,  0.75566313,  0.6892601 ],
       [-1.14770141,  0.11420755, -1.28142619, -1.4521305 ],
       [-0.24670217, -0.35036553, -0.05917259,  0.15391245],
       [ 1.16915377,  0.57878063,  1.163081  ,  1.7599554 ],
       [ 0.39686871, -0.58265207,  0.58105548,  0.02007554],
       [-0.50413053,  1.50792679, -1.28142619, -1.31829359],
       [ 0.39686871, -0.11807899,  0.52285293,  0.28774936],
       [ 0.01072618, -0.58265207,  0.81386569,  1.62611849],
       [ 0.52558289, -0.58265207,  0.63925803,  0.82309701],
       [-1.66255812, -1.74408477, -1.39783129, -1.18445668],
       [ 0.39686871, -1.04722515,  1.10487845,  0.28774936],
       [ 2.45629554,  1.74021333,  1.74510652,  1.35844466],
       [ 1.42658213,  0.11420755,  0.81386569,  1.49228158],
       [ 0.78301124,  0.

In [21]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [23]:
y_pred = classifier.predict(X_test) 
y_pred


array(['versicolor', 'setosa', 'versicolor', 'virginica', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'virginica', 'setosa', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'setosa', 'setosa', 'setosa',
       'versicolor', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')

In [25]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0,  6,  1],
       [ 0,  2, 11]], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9


In [29]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   versicolor       versicolor
1       setosa           setosa
2   versicolor       versicolor
3   versicolor        virginica
4       setosa           setosa
5   versicolor       versicolor
6    virginica        virginica
7   versicolor       versicolor
8       setosa           setosa
9   versicolor       versicolor
10   virginica        virginica
11   virginica        virginica
12      setosa           setosa
13   virginica       versicolor
14   virginica        virginica
15   virginica        virginica
16  versicolor       versicolor
17      setosa           setosa
18      setosa           setosa
19      setosa           setosa
20   virginica       versicolor
21   virginica        virginica
22      setosa           setosa
23      setosa           setosa
24      setosa           setosa
25   virginica        virginica
26   virginica        virginica
27   virginica        virginica
28   virginica        virginica
29   virginica        virginica